install.packages("rpart")
library(rpart)
bank.df <- read.csv("UniversalBank.csv")
bank.df <- bank.df[ , -c(1, 5)]
install.packages("caret")
library(caret)
set.seed(1000)
str(bank.df)
head(bank.df)
intrain<-createDataPartition(y=bank.df$Personal.Loan, p=0.6, list=FALSE)
train<-bank.df[intrain, ]
teat<-bank.df[-intrain, ]
rpartmod<-rpart(Personal.Loan~., data=bank.df, method = "class")
plot(rpartmod)
text(rpartmod)
printcp(rpartmod)
plotcp(rpartmod)
ptree<-prune(rpartmod, cp=rpartmod$cptable[which.min(rpartmod$cptable[,"xerror"]), "CP"])
plot(ptree)
text(ptree)
printcp(ptree)
plotcp(ptree)
rpartpred<-predict(ptree, test, type='class')
confusionMatrix(rpartpred, test$Personal.Loan)

